INSERT INTO INTERNAL.ORDERS (ID, CREATED, DEADLINE, DESCRIPTION, CREATED_BY, MODIFIED_BY, CREATED_FOR_ID)
VALUES ( 501, CURRENT_TIMESTAMP(),  CURRENT_TIMESTAMP(), 'Order one', 24, 25, 91);
INSERT INTO INTERNAL.ORDERS (ID, CREATED, FINISHED, DEADLINE, DESCRIPTION, OVERALL_PRICE, CREATED_BY, MODIFIED_BY, CREATED_FOR_ID)
VALUES ( 502, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Order two', 78.56, 27, 25, 92 );
INSERT INTO INTERNAL.ORDERS (ID, CREATED, FINISHED, DEADLINE, DESCRIPTION, OVERALL_PRICE, CREATED_BY, MODIFIED_BY, CREATED_FOR_ID)
VALUES ( 503, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Order three', 25.50, 22, 26, 93 );