export const SET_DISPLAY_BLOCK = "SET_DISPLAY_BLOCK";
export const SET_DISPLAY_NONE = "SET_DISPLAY_NONE";
export const SET_BACKGROUND_COLOR = "SET_BACKGROUND_COLOR";
export const SET_DISPLAY_RIGHT_MENU = "SET_DISPLAY_RIGHT_MENU";
export const SET_DISPLAY_RIGHT_CHAT = "SET_DISPLAY_RIGHT_CHAT";
export const SET_DISPLAY_RIGHT_TODO = "SET_DISPLAY_RIGHT_TODO";
export const SET_DISPLAY_CENTER_LEFT_ORDERS = "SET_DISPLAY_CENTER_LEFT_ORDERS";