-- HIBERNATE SPECIAL IMPORT AFTER ALL THE SCHEMAS HAVE BEEN SET FROM 'schema.sql' AND THE TABLES HAVE BEEN CREATED AUTOMATICALLY
-- SUPPORTS ONLY INLINE STRINGS!
INSERT INTO INTERNAL.EMPLOYEES (ID, EMAIL, FIRST_NAME, LAST_NAME, PASSWORD, PHONE) VALUES ( 1, 'employee@shop.pro', 'EmpName', 'EmpLastName' , '123', '1234567');
