-- HIBERNATE SPECIAL IMPORT AFTER ALL THE SCHEMAS HAVE BEEN SET FROM 'schema.sql' AND THE TABLES HAVE BEEN CREATED AUTOMATICALLY
-- SUPPORTS ONLY INLINE STRINGS!
INSERT INTO INTERNAL.EMPLOYEES (ID, EMAIL, FIRST_NAME, LAST_NAME, BIRTHDAY, PASSWORD, PHONE)VALUES (1, 'employee@shop.pro', 'EmpName', 'EmpLastName', DATE '1970-07-25', '123', '123456789');
